# src/omr_pipeline/header_injector.py
"""
Virtual header injector for continuation-staff CRNN inference.

Loads prerendered clef+key+time strip templates from ``data/header_templates/``
(generated by ``src/data_processing/generate_header_templates.py``) and
prepends them to staff images before the CRNN so the model always sees a
full-header staff matching its training distribution.

If a template is missing, ``inject_header`` returns the staff image unchanged
and logs a warning.
"""

from __future__ import annotations

import logging
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

log = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "header_templates"


def _template_path(key: str, time_tuple: tuple[str, str, str]) -> Path:
    """Map (key string, time tuple) → template PNG path.

    Args:
        key: e.g. ``"key:fifths:-2"``
        time_tuple: e.g. ``("time", "beats:4", "beat-type:4")``
    """
    fifths = int(key.split(":")[2])
    beats = int(time_tuple[1].split(":")[1])
    beat_type = int(time_tuple[2].split(":")[1])
    return TEMPLATES_DIR / f"key_{fifths}_time_{beats}_{beat_type}.png"


def load_template(key: str, time_tuple: tuple[str, str, str]) -> np.ndarray | None:
    """Load the header template for *key* + *time_tuple*.

    Returns a grayscale uint8 ndarray, or ``None`` if the template file is
    missing (templates not yet generated).
    """
    path = _template_path(key, time_tuple)
    if not path.exists():
        log.warning(
            "Header template not found: %s — run 'cli.py generate-header-templates'",
            path.name,
        )
        return None
    return np.array(Image.open(path).convert("L"))


def inject_header(
    staff_img: np.ndarray,
    key: str,
    time_tuple: tuple[str, str, str],
) -> np.ndarray:
    """Prepend the matching header template to *staff_img*.

    The template is resized to match the staff image height (preserving aspect
    ratio) before horizontal concatenation. If the template is missing, the
    original *staff_img* is returned unchanged.

    Args:
        staff_img: Grayscale uint8 ndarray, shape (H, W).
        key: e.g. ``"key:fifths:-2"``
        time_tuple: e.g. ``("time", "beats:4", "beat-type:4")``
    """
    template = load_template(key, time_tuple)
    if template is None:
        return staff_img

    h = staff_img.shape[0]
    th, tw = template.shape[:2]
    new_w = max(1, round(tw * h / th))
    resized = cv2.resize(template, (new_w, h), interpolation=cv2.INTER_AREA)
    return np.concatenate([resized, staff_img], axis=1)
