"""
chord_train.py
==============
Training entry point for the **chord CRNN**.

A dedicated CRNN/CTC model that recognises Real Book chord text.  It uses
the same model class as the music CRNN (``model.CRNN``) but:

* a smaller image height (64 px vs 128 — chord text is simpler);
* a character-level vocabulary (~30 tokens);
* a synthetic training set generated by ``data_processing.generate_chord_crops``;
* heavier Albumentations augmentation to bridge the visual gap between
  LilyJAZZ renders and real Real Book scans.

Usage::

    poetry run python src/CRNN_CTC/chord_train.py \
        --data-dir data/chord_synth --epochs 30
"""

from __future__ import annotations

import argparse
import csv
import logging
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import torch
import torch.nn as nn
from torch.amp import GradScaler
from torch.optim import AdamW
from torch.optim.lr_scheduler import OneCycleLR
from torch.utils.data import DataLoader

from .chord_dataset import ChordDataset, build_chord_vocab, collate_fn
from .model import CRNN
from .training_utils import (
    create_run_dir,
    seed_everything,
    train_one_epoch,
    validate_ctc_epoch,
)
from .vocab import Vocabulary

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class ChordConfig:
    """Chord CRNN training configuration — serialised inside every checkpoint."""

    # Paths
    data_dir: Path = Path("data/chord_synth")
    model_dir: Path = Path("models/chord")
    vocab_path: Path = Path("data/vocab/chord.txt")

    # Reproducibility
    seed: int = 42

    # Image
    img_height: int = 64
    max_image_width: int = 2048

    # Model — smaller than the music CRNN; chord text is simpler
    backbone: str = "resnet18"
    cnn_out_channels: int = 256
    cnn_dropout: float = 0.15
    rnn_hidden: int = 192
    rnn_layers: int = 2
    dropout: float = 0.2

    # Augmentation
    augment: bool = True

    # Training
    epochs: int = 30
    batch_size: int = 32
    lr: float = 1e-3
    weight_decay: float = 1e-4
    warmup_frac: float = 0.05
    num_workers: int = 6
    early_stopping_patience: int = 8
    max_grad_norm: float = 5.0

    def __post_init__(self) -> None:
        self.model_dir.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Vocab bootstrap
# ---------------------------------------------------------------------------


def _ensure_vocab(cfg: ChordConfig) -> Vocabulary:
    """Load the chord vocabulary; build it from train_labels.csv on first use."""
    if cfg.vocab_path.exists():
        return Vocabulary.from_file(cfg.vocab_path)

    train_labels = cfg.data_dir / "train_labels.csv"
    val_labels = cfg.data_dir / "val_labels.csv"
    sources = [p for p in (train_labels, val_labels) if p.exists()]
    if not sources:
        raise FileNotFoundError(f"No labels CSV under {cfg.data_dir}; generate the dataset first.")
    log.info("Building chord vocab from %s", sources)
    vocab = build_chord_vocab(sources)
    cfg.vocab_path.parent.mkdir(parents=True, exist_ok=True)
    vocab.save(cfg.vocab_path)
    log.info("Wrote chord vocab → %s (%d tokens incl. blank/pad/unk)", cfg.vocab_path, len(vocab))
    return vocab


# ---------------------------------------------------------------------------
# Train
# ---------------------------------------------------------------------------


def train(cfg: ChordConfig) -> Path:
    seed_everything(cfg.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    use_amp = device.type == "cuda"
    if use_amp:
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True
    log.info("Device: %s | AMP: %s", device, use_amp)

    run_dir = create_run_dir(cfg.model_dir)
    log.info("Run directory: %s", run_dir)

    vocab = _ensure_vocab(cfg)
    log.info("Vocabulary: %d tokens", len(vocab))

    train_ds = ChordDataset(
        image_dir=cfg.data_dir / "train",
        labels_csv=cfg.data_dir / "train_labels.csv",
        vocab=vocab,
        img_height=cfg.img_height,
        max_image_width=cfg.max_image_width,
        augment=cfg.augment,
    )
    val_ds = ChordDataset(
        image_dir=cfg.data_dir / "val",
        labels_csv=cfg.data_dir / "val_labels.csv",
        vocab=vocab,
        img_height=cfg.img_height,
        max_image_width=cfg.max_image_width,
        augment=False,
    )

    train_loader = DataLoader(
        train_ds,
        batch_size=cfg.batch_size,
        shuffle=True,
        num_workers=cfg.num_workers,
        collate_fn=collate_fn,
        pin_memory=use_amp,
        drop_last=True,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=cfg.batch_size,
        shuffle=False,
        num_workers=cfg.num_workers,
        collate_fn=collate_fn,
        pin_memory=use_amp,
    )

    model = CRNN(
        vocab_size=len(vocab),
        cnn_out_channels=cfg.cnn_out_channels,
        rnn_hidden=cfg.rnn_hidden,
        rnn_layers=cfg.rnn_layers,
        dropout=cfg.dropout,
        cnn_dropout=cfg.cnn_dropout,
        backbone=cfg.backbone,
    ).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    log.info("Model params: %.2fM", n_params / 1e6)

    criterion = nn.CTCLoss(blank=vocab.blank_idx, zero_infinity=True)
    optimiser = AdamW(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)

    total_steps = len(train_loader) * cfg.epochs
    scheduler = OneCycleLR(
        optimiser,
        max_lr=cfg.lr,
        total_steps=total_steps,
        pct_start=cfg.warmup_frac,
        anneal_strategy="cos",
    )
    scaler = GradScaler("cuda", enabled=use_amp)

    # Training log
    log_csv = run_dir / "training_log.csv"
    with open(log_csv, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["epoch", "train_loss", "val_loss", "val_cer", "elapsed_s"])

    best_cer = float("inf")
    best_path = run_dir / "best_model.pt"
    epochs_since_improve = 0

    for epoch in range(1, cfg.epochs + 1):
        t0 = time.time()
        train_loss = train_one_epoch(
            model,
            train_loader,
            criterion,
            optimiser,
            scheduler,
            scaler,
            device,
            use_amp,
            cfg.max_grad_norm,
        )
        val_loss, val_cer = validate_ctc_epoch(
            model,
            val_loader,
            criterion,
            vocab,
            device,
            use_amp,
        )
        dt = time.time() - t0

        log.info(
            "Epoch %d/%d  train=%.4f  val=%.4f  CER=%.4f  (%.1fs)",
            epoch,
            cfg.epochs,
            train_loss,
            val_loss,
            val_cer,
            dt,
        )
        with open(log_csv, "a", newline="") as f:
            csv.writer(f).writerow([epoch, train_loss, val_loss, val_cer, dt])

        # Always save latest
        torch.save(
            {
                "epoch": epoch,
                "model_state": model.state_dict(),
                "optimiser_state": optimiser.state_dict(),
                "scheduler_state": scheduler.state_dict(),
                "scaler_state": scaler.state_dict(),
                "config": asdict(cfg),
                "vocab_tokens": vocab._idx2tok[3:],  # content tokens only
                "val_cer": val_cer,
                "val_loss": val_loss,
            },
            run_dir / "latest_checkpoint.pt",
        )

        # Save best
        if val_cer < best_cer:
            best_cer = val_cer
            epochs_since_improve = 0
            torch.save(
                {
                    "epoch": epoch,
                    "model_state": model.state_dict(),
                    "config": asdict(cfg),
                    "vocab_tokens": vocab._idx2tok[3:],
                    "val_cer": val_cer,
                    "val_loss": val_loss,
                },
                best_path,
            )
            log.info("  ↳ new best CER: %.4f  saved → %s", best_cer, best_path)
        else:
            epochs_since_improve += 1
            if cfg.early_stopping_patience > 0 and epochs_since_improve >= cfg.early_stopping_patience:
                log.info("Early stopping: no val-CER improvement for %d epochs", epochs_since_improve)
                break

    log.info("Training complete.  Best CER: %.4f  →  %s", best_cer, best_path)
    return best_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--data-dir", default="data/chord_synth")
    p.add_argument("--model-dir", default="models/chord")
    p.add_argument("--vocab-path", default="data/vocab/chord.txt")
    p.add_argument("--epochs", type=int, default=30)
    p.add_argument("--batch-size", type=int, default=32)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--img-height", type=int, default=64)
    p.add_argument("--num-workers", type=int, default=6)
    p.add_argument("--no-augment", action="store_true")
    p.add_argument("--log-level", default="INFO")
    args = p.parse_args()

    logging.basicConfig(
        level=args.log_level,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    cfg = ChordConfig(
        data_dir=Path(args.data_dir),
        model_dir=Path(args.model_dir),
        vocab_path=Path(args.vocab_path),
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        img_height=args.img_height,
        num_workers=args.num_workers,
        augment=not args.no_augment,
    )
    train(cfg)


if __name__ == "__main__":
    main()
